name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run:
          pip install poetry
      - run:
          poetry install
      - run:
          poetry build
      - run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi -u __token__ -p ${{ secrets.POETRY_HTTP_BASIC_TESTPYPI_PASSWORD }}
          


  # publish-package-test-pypi: 
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Publish package to TestPyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/
